modify position to right
stevenjoezhang/live2d-widget pull request #74
Opened 2021-05-01 01:34 UTC by ZKQevin

2021-05-01 02:49 UTC, KnowsCount commented on autoload.js
> +const live2d_path = const live2d_path = "https://cdn.jsdelivr.net/gh/ZKQevin/live2d-widget/";
`const live2d_path` 为什么要写两遍？
为什么要换成你的 URL？

2021-05-01 02:51 UTC, KnowsCount requested changes
我没有看懂，为什么要提这样一个 PR？

`const live2d_path = const live2d_path = "https://cdn.jsdelivr.net/gh/ZKQevin/live2d-widget/";` 这句有错误；并且，原来在左边蛮好的，你要调节可以自己弄，不需要提 PR 吧。

2021-05-01 03:47 UTC, ZKQevin commented
好的，谢谢您哈，我不是很懂这个东西，望您见谅




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月1日(星期六) 上午10:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stevenjoezhang/live2d-widget] modify position to right (#74)





 
@KnowsCount requested changes on this pull request.
 
我没有看懂，为什么要提这样一个 PR？
 
const live2d_path = const live2d_path = "https://cdn.jsdelivr.net/gh/ZKQevin/live2d-widget/"; 这句有错误；并且，原来在左边蛮好的，你要调节可以自己弄，不需要提 PR 吧。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2022-10-19 10:17 UTC, stevenjoezhang commented
感谢您提交的 Pull Request！我会在近期调整相关功能。您也可以参考一下这些更灵活的方案： https://github.com/stevenjoezhang/live2d-widget/pull/64 https://github.com/stevenjoezhang/live2d-widget/pull/108

2022-10-19 10:17 UTC, closed without merging